# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Playblast.ui'
#
# Created: Mon Dec 16 17:41:27 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Playblast(object):
    def setupUi(self, Playblast):
        Playblast.setObjectName("Playblast")
        Playblast.resize(469, 624)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Playblast)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtGui.QLabel(Playblast)
        self.label_10.setMinimumSize(QtCore.QSize(120, 0))
        self.label_10.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.widthEdit = QtGui.QLineEdit(Playblast)
        self.widthEdit.setObjectName("widthEdit")
        self.horizontalLayout_4.addWidget(self.widthEdit)
        self.heightEdit = QtGui.QLineEdit(Playblast)
        self.heightEdit.setObjectName("heightEdit")
        self.horizontalLayout_4.addWidget(self.heightEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(Playblast)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.frameStart = QtGui.QLineEdit(Playblast)
        self.frameStart.setObjectName("frameStart")
        self.horizontalLayout.addWidget(self.frameStart)
        self.frameEnd = QtGui.QLineEdit(Playblast)
        self.frameEnd.setObjectName("frameEnd")
        self.horizontalLayout.addWidget(self.frameEnd)
        self.fromTimeLineButton = QtGui.QPushButton(Playblast)
        self.fromTimeLineButton.setObjectName("fromTimeLineButton")
        self.horizontalLayout.addWidget(self.fromTimeLineButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(Playblast)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sizeWidget = QtGui.QWidget(Playblast)
        self.sizeWidget.setObjectName("sizeWidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.sizeWidget)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.size25 = QtGui.QRadioButton(self.sizeWidget)
        self.size25.setObjectName("size25")
        self.verticalLayout_5.addWidget(self.size25)
        self.size50 = QtGui.QRadioButton(self.sizeWidget)
        self.size50.setObjectName("size50")
        self.verticalLayout_5.addWidget(self.size50)
        self.size75 = QtGui.QRadioButton(self.sizeWidget)
        self.size75.setObjectName("size75")
        self.verticalLayout_5.addWidget(self.size75)
        self.size100 = QtGui.QRadioButton(self.sizeWidget)
        self.size100.setChecked(True)
        self.size100.setObjectName("size100")
        self.verticalLayout_5.addWidget(self.size100)
        self.horizontalLayout_2.addWidget(self.sizeWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(Playblast)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.widget = QtGui.QWidget(Playblast)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formatQuicktime = QtGui.QRadioButton(self.widget)
        self.formatQuicktime.setChecked(True)
        self.formatQuicktime.setObjectName("formatQuicktime")
        self.verticalLayout_3.addWidget(self.formatQuicktime)
        self.formatTiff = QtGui.QRadioButton(self.widget)
        self.formatTiff.setObjectName("formatTiff")
        self.verticalLayout_3.addWidget(self.formatTiff)
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtGui.QLabel(Playblast)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.cameraCombo = QtGui.QComboBox(Playblast)
        self.cameraCombo.setMinimumSize(QtCore.QSize(0, 0))
        self.cameraCombo.setObjectName("cameraCombo")
        self.gridLayout.addWidget(self.cameraCombo, 1, 1, 1, 1)
        self.setViewButton = QtGui.QPushButton(Playblast)
        self.setViewButton.setObjectName("setViewButton")
        self.gridLayout.addWidget(self.setViewButton, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(Playblast)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.widget_2 = QtGui.QWidget(Playblast)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stereoOff = QtGui.QRadioButton(self.widget_2)
        self.stereoOff.setChecked(True)
        self.stereoOff.setObjectName("stereoOff")
        self.verticalLayout_4.addWidget(self.stereoOff)
        self.stereoAna = QtGui.QRadioButton(self.widget_2)
        self.stereoAna.setObjectName("stereoAna")
        self.verticalLayout_4.addWidget(self.stereoAna)
        self.stereoMulti = QtGui.QRadioButton(self.widget_2)
        self.stereoMulti.setObjectName("stereoMulti")
        self.verticalLayout_4.addWidget(self.stereoMulti)
        self.horizontalLayout_5.addWidget(self.widget_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtGui.QLabel(Playblast)
        self.label_6.setMinimumSize(QtCore.QSize(120, 0))
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.playwithCombo = QtGui.QComboBox(Playblast)
        self.playwithCombo.setMinimumSize(QtCore.QSize(0, 0))
        self.playwithCombo.setObjectName("playwithCombo")
        self.horizontalLayout_6.addWidget(self.playwithCombo)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.checkBox = QtGui.QCheckBox(Playblast)
        self.checkBox.setEnabled(False)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_6.addWidget(self.checkBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtGui.QLabel(Playblast)
        self.label_7.setEnabled(False)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        self.label_7.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.checkBox_2 = QtGui.QCheckBox(Playblast)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_7.addWidget(self.checkBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtGui.QLabel(Playblast)
        self.label_8.setMinimumSize(QtCore.QSize(120, 0))
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.overscan = QtGui.QCheckBox(Playblast)
        self.overscan.setText("")
        self.overscan.setChecked(True)
        self.overscan.setObjectName("overscan")
        self.horizontalLayout_8.addWidget(self.overscan)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtGui.QLabel(Playblast)
        self.label_9.setMinimumSize(QtCore.QSize(120, 0))
        self.label_9.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.soundCheck = QtGui.QCheckBox(Playblast)
        self.soundCheck.setText("")
        self.soundCheck.setChecked(True)
        self.soundCheck.setObjectName("soundCheck")
        self.horizontalLayout_9.addWidget(self.soundCheck)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtGui.QLabel(Playblast)
        self.label_12.setMinimumSize(QtCore.QSize(120, 0))
        self.label_12.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.ornamentsCheck = QtGui.QCheckBox(Playblast)
        self.ornamentsCheck.setText("")
        self.ornamentsCheck.setObjectName("ornamentsCheck")
        self.horizontalLayout_11.addWidget(self.ornamentsCheck)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtGui.QLabel(Playblast)
        self.label_11.setMinimumSize(QtCore.QSize(120, 0))
        self.label_11.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.widthFinalEdit = QtGui.QLineEdit(Playblast)
        self.widthFinalEdit.setEnabled(False)
        self.widthFinalEdit.setObjectName("widthFinalEdit")
        self.horizontalLayout_10.addWidget(self.widthFinalEdit)
        self.heightFinalEdit = QtGui.QLineEdit(Playblast)
        self.heightFinalEdit.setEnabled(False)
        self.heightFinalEdit.setObjectName("heightFinalEdit")
        self.horizontalLayout_10.addWidget(self.heightFinalEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.playBlastButton = QtGui.QPushButton(Playblast)
        self.playBlastButton.setMinimumSize(QtCore.QSize(0, 45))
        self.playBlastButton.setObjectName("playBlastButton")
        self.verticalLayout_2.addWidget(self.playBlastButton)
        self.playLatestButton = QtGui.QPushButton(Playblast)
        self.playLatestButton.setObjectName("playLatestButton")
        self.verticalLayout_2.addWidget(self.playLatestButton)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)

        self.retranslateUi(Playblast)
        QtCore.QObject.connect(self.size25, QtCore.SIGNAL("clicked()"), Playblast.updateOutputResolution)
        QtCore.QObject.connect(self.size50, QtCore.SIGNAL("clicked()"), Playblast.updateOutputResolution)
        QtCore.QObject.connect(self.size75, QtCore.SIGNAL("clicked()"), Playblast.updateOutputResolution)
        QtCore.QObject.connect(self.size100, QtCore.SIGNAL("clicked()"), Playblast.updateOutputResolution)
        QtCore.QObject.connect(self.widthEdit, QtCore.SIGNAL("textChanged(QString)"), Playblast.updateOutputResolution)
        QtCore.QObject.connect(self.heightEdit, QtCore.SIGNAL("textChanged(QString)"), Playblast.updateOutputResolution)
        QtCore.QMetaObject.connectSlotsByName(Playblast)

    def retranslateUi(self, Playblast):
        Playblast.setWindowTitle(QtGui.QApplication.translate("Playblast", "Playblast", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Playblast", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.widthEdit.setText(QtGui.QApplication.translate("Playblast", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.heightEdit.setText(QtGui.QApplication.translate("Playblast", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Playblast", "Frame range: ", None, QtGui.QApplication.UnicodeUTF8))
        self.fromTimeLineButton.setText(QtGui.QApplication.translate("Playblast", "From timeline", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Playblast", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.size25.setText(QtGui.QApplication.translate("Playblast", "25%", None, QtGui.QApplication.UnicodeUTF8))
        self.size50.setText(QtGui.QApplication.translate("Playblast", "50%", None, QtGui.QApplication.UnicodeUTF8))
        self.size75.setText(QtGui.QApplication.translate("Playblast", "75%", None, QtGui.QApplication.UnicodeUTF8))
        self.size100.setText(QtGui.QApplication.translate("Playblast", "100%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Playblast", "Output: ", None, QtGui.QApplication.UnicodeUTF8))
        self.formatQuicktime.setText(QtGui.QApplication.translate("Playblast", "Quicktime", None, QtGui.QApplication.UnicodeUTF8))
        self.formatTiff.setText(QtGui.QApplication.translate("Playblast", "Tiff", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Playblast", "Camera:", None, QtGui.QApplication.UnicodeUTF8))
        self.setViewButton.setText(QtGui.QApplication.translate("Playblast", "Set view to camera!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Playblast", "Stereo options: ", None, QtGui.QApplication.UnicodeUTF8))
        self.stereoOff.setText(QtGui.QApplication.translate("Playblast", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.stereoAna.setText(QtGui.QApplication.translate("Playblast", "Anaglyph in Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.stereoMulti.setText(QtGui.QApplication.translate("Playblast", "Both Eyes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Playblast", "Play with: ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Playblast", "Open when done", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Playblast", "Submit to Dailies: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Playblast", "Overscan 1,0:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Playblast", "Add sound if exists", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Playblast", "Show ornamens: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Playblast", "Output resolution: ", None, QtGui.QApplication.UnicodeUTF8))
        self.playBlastButton.setText(QtGui.QApplication.translate("Playblast", "Playblast!", None, QtGui.QApplication.UnicodeUTF8))
        self.playLatestButton.setText(QtGui.QApplication.translate("Playblast", "Play latest!", None, QtGui.QApplication.UnicodeUTF8))

